
<?php
include 'conexion.php';
$USUACODIGO = $_POST['USUACODIGO'];
$USUANOMBRE = $_POST['USUANOMBRE'];
$USUAUSUARIO = $_POST ['USUAUSUARIO'];
$USUAPASSWORD = $_POST['USUAPASSWORD'];
$USUA_CORREO = $_POST['USUA_CORREO'];

mysqli_query($conexion,"INSERT INTO usuario(USUACODIGO,USUANOMBRE,USUAUSUARIO,USUAPASSWORD,USUA_CORREO)
VALUES( '$USUACODIGO','$USUANOMBRE','$USUAUSUARIO','$USUAPASSWORD','$USUA_CORREO')");
header("Location:index.php");

?>



